<a href="https://colab.research.google.com/github/bmounikareddy98/Machine-learning-assignments/blob/main/Multiple_linear_regression(gradient_descent).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd  
import seaborn as sns 
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import SGDRegressor

In [101]:
url = 'https://raw.githubusercontent.com/bmounikareddy98/Machine-learning-assignments/main/insurance.csv'
dataset = pd.read_csv(url)
dataset=dataset.dropna()
dataset = dataset.drop_duplicates()
print(dataset.head())

      sex smoker     region  children     bmi  age      charges
0  female    yes  southwest         0  27.900   19  16884.92400
1    male     no  southeast         1  33.770   18   1725.55230
2    male     no  southeast         3  33.000   28   4449.46200
3    male     no  northwest         0  22.705   33  21984.47061
4    male     no  northwest         0  28.880   32   3866.85520


In [102]:
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values
print(X.shape)
print(Y.shape)
print(X[5])
#print(Y[5])
print(type(dataset))


(1337, 6)
(1337,)
['female' 'no' 'southeast' 0 25.74 31]
<class 'pandas.core.frame.DataFrame'>


In [103]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
X[:, 0] = labelencoder.fit_transform(X[:, 0])
X[:, 1]= labelencoder.fit_transform(X[:, 1])
X[:, 2]= labelencoder.fit_transform(X[:, 2])
print(X)

[[0 1 3 0 27.9 19]
 [1 0 2 1 33.77 18]
 [1 0 2 3 33.0 28]
 ...
 [0 0 2 0 36.85 18]
 [0 0 3 0 25.8 21]
 [0 1 1 0 29.07 61]]


In [104]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,1,2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))


print(X[1])
#print(X.shape)

[0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 1 33.77 18]


In [105]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)

In [106]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(1069, 11)
(1069,)
(268, 11)
(268,)


In [113]:
nrows,ncols = X_train.shape[0],X_train.shape[1]
W = np.random.rand(ncols).reshape(ncols, 1)
print(W.shape)
print(nrows)
print(ncols)
print(np.dot(X_train,W))

(11, 1)
1069
11
[[37.51690892280365]
 [27.51337249238559]
 [29.59437024710261]
 ...
 [34.722131615449555]
 [24.977239263667094]
 [43.87828411854198]]


In [114]:
def trainData(X,Y,W, epochs, learning_rate):
        # Perform Gradient Descent
        for i in range(epochs):
            # Make prediction with current weights
            h = np.dot(X, W)
            # Find error
            error = h - Y
            W = W - (1 / nrows) * learning_rate * np.dot(X.T, error)

        return W, error

In [116]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train[:, 8:11] = sc.fit_transform(X_train[:, 8:11])
X_test[:, 8:11] = sc.transform(X_test[:, 8:11])
Y_train = Y_train.reshape(-1, 1)
Y_train = sc.fit_transform(Y_train)
Y_test = Y_test.reshape(-1, 1)
Y_test = sc.fit_transform(Y_test)
print(X_train[0])
print(X_test[0])
print(Y_train)
print(Y_train.shape)
print(X_train.shape)

[0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 1.5855501703442836 0.41411571577417966
 1.4894065185340781]
[1.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 -0.9205412028908664 1.3864435332426204
 0.3455508724918316]
[[ 0.02352913]
 [-0.0505176 ]
 [-0.34135011]
 ...
 [-0.97548154]
 [ 0.47423484]
 [ 2.88308022]]
(1069, 1)
(1069, 11)


In [124]:
def predict(X_train,X_test,name,theta):
        if name=='X_train':
            nrows, ncols = X_train.shape[0], X_train.shape[1]
            #t_X = X_train[:, 0:(ncols)].reshape(nrows, ncols)
            #t_Y = X_train[:, (ncols)].reshape(nrows, 1)
            t_X = X_train[:, 0:(ncols)]
            t_Y = X_train[:, (ncols-1)]
        else:
            nrows, ncols = X_test.shape[0], X_test.shape[1]
            #t_X = X_test[:, 0:(ncols )].reshape(nrows, ncols)
            #t_Y = X_test[:, (ncols)].reshape(nrows, 1)
            t_X = X_test[:, 0:(ncols)]
            t_Y = X_test[:, (ncols-1)]
            
        
        #t_X =sc.fit_transform(X_train[:, 8:11])
        pred = np.dot(t_X, theta)
        error = pred - t_Y
        mse = (1/(2*nrows)) * np.dot(error.T, error)
        return mse

In [121]:
print(W.shape)
print(X_train.shape)
print(np.dot(X_train[:,0:11],W[:,0:11]))

(11, 1)
(1069, 11)
[[3.4307504041607544]
 [0.4763660417995279]
 [0.7096193167397105]
 ...
 [2.5953594768923636]
 [0.4374347191930063]
 [3.8471973572075893]]


In [ ]:
mse_train = []
epochs = [50,150,300,450,1000]
learning_rate = [0.01,0.1,1.9,2]
for i in epochs:
  for j in learning_rate:
        theta,error = trainData(X_train,Y_train,W,i,j)
        mse_train.append(predict(X_train,X_test,'X_train',theta))
mse_train_1 = np.array(mse_train)
mse_train_1 = mse_train_1.reshape(-1,1)
print(mse_train_1)
print(np.min(mse_train_1))
print(type(mse_train))